export const Carpets = {
  // Aksiya: [
  //   {
  //     id: "aksiya-001",
  //     countri:
  //       "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
  //     image: "https://mahkamov-images.netlify.app/eron/IMG_8586.webp",
  //     image1: "https://mahkamov-images.netlify.app/eron/IMG_8589.webp",
  //     rotate: "-rotate-90",
  //     price: 122,
  //     typeProduct: "2x3",
  //     demoPrice: 133,
  //     aboutProduct: "Eron Collection",
  //     zichligi: "1 m² ga 2880000 tugun",
  //     material: "100% paxta",
  //     ipBalandligi: "7mm",
  //   },
  //   {
  //     id: "aksiya-002",
  //     countri:
  //       "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
  //     image: "https://mahkamov-images.netlify.app/eron/IMG_8591.webp",
  //     image1: "https://mahkamov-images.netlify.app/eron/IMG_8589.webp",
  //     rotate: "rotate-90",
  //     price: 122,
  //     typeProduct: "2x3",
  //     demoPrice: 133,
  //     aboutProduct: "Eron Collection",
  //     zichligi: "1 m² ga 2880000 tugun",
  //     material: "100% paxta",
  //     ipBalandligi: "7mm",
  //   },
  // ],
  Eron: [
    //! Naval
    {
      id: "eron-001",
      countri:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
      image: "https://mahkamov-images.netlify.app/eron/IMG_8586.webp",
      image1: "https://mahkamov-images.netlify.app/eron/IMG_8589.webp",
      design: "g401",
      rotate: "-rotate-90",
      price: 45,
      typeProduct: [
        "1x2",
        "1x25",
        "1.5x25",
        "1.5x2.25",
        "1.2x25",
        "2x25",
        "3x4",
        "3.5x5",
        "3.5x6",
        "4x4",
        "4x5",
        "4x7",
        "4x8",
      ],
      demoPrice: 100,
      aboutProduct: "Naval Eron Collection",
      zichligi: "1.200.000 taroq",
      material: "100% paxta",
      ipBalandligi: "7mm",
    },
    //! Ghetaran
    {
      id: "eron-002",
      countri:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
      image: "https://mahkamov-images.netlify.app/eron/IMG_8591.webp",
      image1: "https://mahkamov-images.netlify.app/eron/IMG_8592.webp",
      design: "g143",
      rotate: "rotate-90",
      price: 50,
      typeProduct: ["1.5x2.5", "2x3", "2.5x3.5", "3x4", "4x6"],
      demoPrice: 100,
      aboutProduct: "Ghetaran Eron Collection",
      zichligi: "1.500.000 taroq",
      material: "100% paxta",
      ipBalandligi: "7mm",
    },
    //! Ghetaran Fill
    {
      id: "eron-003",
      countri:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
      image: "https://mahkamov-images.netlify.app/eron/IMG_8593.webp",
      image1: "",
      design: "g382",
      rotate: "rotate-90",
      price: 50,
      typeProduct: ["1.5x2.25", "3x4", "4x5", "4x6", "4x7", "4x8"],
      demoPrice: 100,
      aboutProduct: "Ghetaran Fill Eron Collection",
      zichligi: "1.500.000 taroq",
      material: "100% paxta",
      ipBalandligi: "7mm",
    },
    // //! ferdows
    {
      id: "eron-004",
      countri:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
      image: "https://mahkamov-images.netlify.app/eron/IMG_8644.webp",
      image1: "",
      design: "g499",
      rotate: "rotate-90",
      price: 50,
      typeProduct: [
        "1x2",
        "1.2x2.25",
        "2.5x3.5",
        "2x2",
        "2x3",
        "3x4",
        "3x5",
        "3.5x6",
        "4x5",
        "4x6",
        "4x7",
        "4x8",
      ],
      demoPrice: 100,
      aboutProduct: "Ghetaran Ferdows Eron Collection",
      zichligi: "1.500.000 taroq",
      material: "100% paxta",
      ipBalandligi: "7mm",
    },
    //! modol
    {
      id: "eron-005",
      countri:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
      image: "https://mahkamov-images.netlify.app/eron/IMG_8653.webp",
      image1: "",
      design: "madal",
      rotate: "rotate-90",
      price: 80,
      typeProduct: [
        "1x2",
        "1.5x2.3",
        "1.5x1.5",
        "2x2",
        "2x3",
        "2.5x4",
        "3x3",
        "3x6",
        "3.5x5",
        "3.5x6",
        "4x4",
        "4x5",
        "4x6",
        "4x7",
        "4x8",
      ],
      demoPrice: 180,
      aboutProduct: "Ghetaran Ferdows Eron Collection",
      zichligi: "1.500.000 taroq",
      material: "100% paxta",
      ipBalandligi: "7mm",
    },
    //! Ferdows
    {
      id: "eron-006",
      countri:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
      image: "https://mahkamov-images.netlify.app/eron/IMG_8647.webp",
      image1: "",
      design: "g364",
      rotate: "rotate-90",
      price: 50,
      typeProduct: [
        "1x2",
        "1.5x2.25",
        "1.5x2.5",
        "2x3",
        "2.5x3.5",
        "3x4",
        "3x5",
        "4x6",
        "4x7",
        "4x8",
      ],
      demoPrice: 100,
      aboutProduct: "Ghetaran Ferdows Eron Collection",
      zichligi: "1.500.000 taroq",
      material: "100% paxta",
      ipBalandligi: "7mm",
    },
    {
      id: "eron-007",
      countri:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
      image: "https://mahkamov-images.netlify.app/eron/IMG_8648.webp",
      image1: "",
      design: "g364",
      rotate: "rotate-90",
      price: 50,
      typeProduct: ["2x3", "1.5x2.25", "2.5x3.5", "3x4"],
      demoPrice: 100,
      aboutProduct: "Ghetaran Ferdows Eron Collection",
      zichligi: "1.500.000 taroq",
      material: "100% paxta",
      ipBalandligi: "7mm",
    },
    {
      id: "eron-008",
      countri:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
      image: "https://mahkamov-images.netlify.app/eron/IMG_8650.webp",
      image1: "",
      design: "g480",
      rotate: "rotate-90",
      price: 45,
      typeProduct: ["1x2", "1.5x2.25", "2x3", "2.5x3.5", "3x4", "3x5"],
      demoPrice: 100,
      aboutProduct: "Ghetaran 1200 Paradis Eron Collection",
      zichligi: "1.500.000 taroq",
      material: "100% paxta",
      ipBalandligi: "7mm",
    },
    {
      id: "eron-009",
      countri:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
      image: "https://mahkamov-images.netlify.app/eron/IMG_8654.webp",
      image1: "",
      design: "victor",
      rotate: "rotate-90",
      price: 80,
      typeProduct: [
        "1x2",
        "1.5x1.5",
        "1.5x2.3",
        "2x3",
        "2.5x3.5",
        "2.5x4",
        "3x4",
        "3x5",
        "3.5x5",
        "3.5x6",
        "4x4",
        "4x5",
        "4x6",
        "4x7",
        "4x8",
      ],
      demoPrice: 180,
      aboutProduct: "Afshar 1500 Madal Eron Collection",
      zichligi: "1.500.000 taroq",
      material: "100% paxta",
      ipBalandligi: "7mm",
    },
    {
      id: "eron-011",
      countri:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
      image: "https://mahkamov-images.netlify.app/eron/IMG_8655.webp",
      image1: "",
      design: "vitor",
      rotate: "rotate-90",
      price: 80,
      typeProduct: [
        "3x4",
        "4x8",
        "3x5",
        "2.5x3.5",
        "2x3",
        "2x2",
        "1.5x1.5",
        "1.5x2.3",
        "3x6",
        "1x2",
        "2.5x4",
        "3x3",
      ],
      demoPrice: 180,
      aboutProduct: "Afshar 1500 Madal Eron Collection",
      zichligi: "1.500.000 taroq",
      material: "100% paxta",
      ipBalandligi: "7mm",
    },
    {
      id: "eron-012",
      countri:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
      image: "https://mahkamov-images.netlify.app/eron/IMG_8658.webp",
      image1: "",
      design: "vitor",
      rotate: "rotate-90",
      price: 80,
      typeProduct: [
        "1x2",
        "1.5x1.5",
        "1.5x2.3",
        "2x2",
        "2x3",
        "2.5x3.5",
        "2.5x4",
        "3x3",
        "3x4",
        "3x5",
        "3x6",
        "3.5x5",
        "3.5x6",
        "4x4",
        "4x5",
        "4x6",
        "4x8",
      ],
      demoPrice: 180,
      aboutProduct: "Afshar 1500 Madal Eron Collection",
      zichligi: "1.500.000 taroq",
      material: "100% paxta",
      ipBalandligi: "7mm",
    },
    {
      id: "eron-013",
      countri:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png",
      image: "https://mahkamov-images.netlify.app/eron/IMG_8660.webp",
      image1: "",
      design: "1323b",
      rotate: "rotate-90",
      price: 75,
      typeProduct: [
        "1x2",
        "1x25",
        "1x1.5",
        "1.5x2.3",
        "1.6x2.3",
        "2x2",
        "2x3",
        "2x4",
        "2.4x3.4",
        "2.5x3.5",
        "2.5x5",
        "3x3",
        "3x4",
        "3x5",
        "3x6",
        "4x4",
        "4x5",
        "4x6",
        "4x7",
        "4x8",
      ],
      demoPrice: 180,
      aboutProduct: "Afshar 1500 Madal Eron Collection",
      zichligi: "1.500.000 taroq",
      material: "100% paxta",
      ipBalandligi: "7mm",
    },
  ],
  // Turkiya: [
  //   {
  //     id: "turkiya-001",
  //     countri:
  //       "https://cdn.britannica.com/82/4782-050-8129909C/Flag-Turkey.jpg",
  //     image: "https://www.sagexpress.uz/media/images/1568_13.jpg",
  //     price: 122,
  //     demoPrice: 133,
  //     typeProduct: "2.5x3.5",
  //     aboutProduct: "Eron Collection",
  //     zichligi: "1 m² ga 2880000 tugun",
  //     material: "100% paxta",
  //     ipBalandligi: "7mm",
  //   },
  //   {
  //     id: "turkiya-002",
  //     countri:
  //       "https://cdn.britannica.com/82/4782-050-8129909C/Flag-Turkey.jpg",
  //     image: "https://www.sagexpress.uz/media/images/1567_83.jpg",
  //     price: 133,
  //     demoPrice: 144,
  //     typeProduct: "3x3",
  //     aboutProduct: "Eron Collection",
  //     zichligi: "1 m² ga 2880000 tugun",
  //     material: "100% paxta",
  //     ipBalandligi: "7mm",
  //   },
  // ],
};
